import type { Assessment, Report, Vulnerability } from './types';

export const mockAssessments: Assessment[] = [
  {
    id: 'ASM-2024-018',
    target: 'https://api.acmecorp.io',
    scanType: 'REST API',
    status: 'Completed',
    date: '2026-07-28',
    duration: '14m 32s',
    critical: 2,
    high: 5,
    medium: 11,
    low: 8,
    riskScore: 78,
    hasPentest: true,
  },
  {
    id: 'ASM-2024-017',
    target: 'https://portal.acmecorp.io',
    scanType: 'Web Application',
    status: 'Completed',
    date: '2026-07-25',
    duration: '22m 10s',
    critical: 1,
    high: 3,
    medium: 7,
    low: 12,
    riskScore: 64,
    hasPentest: false,
  },
  {
    id: 'ASM-2024-016',
    target: '10.0.4.0/24',
    scanType: 'Internal Network',
    status: 'In Progress',
    date: '2026-07-30',
    duration: '—',
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    riskScore: 0,
    hasPentest: false,
  },
  {
    id: 'ASM-2024-015',
    target: 'https://checkout.acmecorp.io',
    scanType: 'Web Application',
    status: 'Pending Approval',
    date: '2026-07-29',
    duration: '—',
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    riskScore: 0,
    hasPentest: false,
  },
  {
    id: 'ASM-2024-014',
    target: 'https://auth.acmecorp.io',
    scanType: 'Web Application',
    status: 'Completed',
    date: '2026-07-20',
    duration: '18m 45s',
    critical: 3,
    high: 4,
    medium: 6,
    low: 9,
    riskScore: 85,
    hasPentest: true,
  },
];

export const mockReports: Report[] = [
  { id: 'RPT-018', assessmentId: 'ASM-2024-018', target: 'api.acmecorp.io', date: '2026-07-28', format: 'PDF', size: '2.4 MB', type: 'Executive' },
  { id: 'RPT-017', assessmentId: 'ASM-2024-017', target: 'portal.acmecorp.io', date: '2026-07-25', format: 'PDF', size: '1.8 MB', type: 'Executive' },
  { id: 'RPT-017-T', assessmentId: 'ASM-2024-017', target: 'portal.acmecorp.io', date: '2026-07-25', format: 'JSON', size: '340 KB', type: 'Technical' },
  { id: 'RPT-014', assessmentId: 'ASM-2024-014', target: 'auth.acmecorp.io', date: '2026-07-20', format: 'PDF', size: '3.1 MB', type: 'Executive' },
  { id: 'RPT-014-S', assessmentId: 'ASM-2024-014', target: 'auth.acmecorp.io', date: '2026-07-20', format: 'SARIF', size: '180 KB', type: 'Compliance' },
];

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: 'VULN-001',
    title: 'SQL Injection in Authentication Endpoint',
    severity: 'Critical',
    cvss: 9.8,
    confidence: 96,
    cwe: 'CWE-89',
    affected: '/api/v2/auth/login',
    description: 'User-supplied email parameter is concatenated directly into a SQL query without parameterization, allowing authentication bypass and potential data exfiltration.',
    businessImpact: 'Full database access including user credentials, PII, and payment tokens. Authentication bypass allows impersonation of any user.',
    threatIntel: 'Active exploitation observed in the wild. Listed in CISA KEV catalog. Associated with APT group tracking.',
    remediation: 'Use parameterized queries / prepared statements for all database interactions. Implement input validation and a WAF rule as interim mitigation. Rotate potentially exposed credentials.',
    attackPath: [
      { step: '1', detail: 'Attacker submits crafted email payload to /api/v2/auth/login' },
      { step: '2', detail: 'Payload bypasses authentication via UNION-based injection' },
      { step: '3', detail: 'Attacker extracts user table including password hashes' },
      { step: '4', detail: 'Credential reuse enables lateral movement to admin panel' },
    ],
    evidence: {
      request: 'POST /api/v2/auth/login HTTP/1.1\nHost: api.acmecorp.io\nContent-Type: application/json\n\n{"email":"admin@acme.io\' OR \'1\'=\'1","password":"x"}',
      response: 'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{"token":"eyJhbG...","user":"admin","role":"superadmin"}',
      poc: "curl -X POST https://api.acmecorp.io/api/v2/auth/login -d '{\"email\":\"admin@acme.io' OR '1'='1\",\"password\":\"x\"}'",
    },
  },
  {
    id: 'VULN-002',
    title: 'Broken Authentication — Weak JWT Signing',
    severity: 'Critical',
    cvss: 9.1,
    confidence: 92,
    cwe: 'CWE-345',
    affected: '/api/v2/auth/token',
    description: 'JWT tokens are signed with a hardcoded symmetric secret stored in source code. The secret is guessable and publicly exposed in the frontend bundle.',
    businessImpact: 'Any attacker can forge valid JWT tokens for arbitrary users, including administrators, leading to complete account takeover.',
    threatIntel: 'Technique documented in MITRE ATT&CK T1550.004. Multiple recent incidents target weak JWT implementations.',
    remediation: 'Rotate the signing key immediately. Move to asymmetric signing (RS256) with keys managed in a vault. Implement key rotation policy and token revocation lists.',
    attackPath: [
      { step: '1', detail: 'Attacker extracts hardcoded secret from frontend JS bundle' },
      { step: '2', detail: 'Forges JWT with admin role claim' },
      { step: '3', detail: 'Accesses admin-only endpoints to modify tenant configurations' },
    ],
    evidence: {
      request: 'GET /api/v2/admin/users HTTP/1.1\nAuthorization: Bearer <forged-token>',
      response: 'HTTP/1.1 200 OK\n\n[{"id":1,"email":"admin@acme.io","role":"superadmin"},...]',
    },
  },
  {
    id: 'VULN-003',
    title: 'Cross-Site Scripting in Support Portal',
    severity: 'High',
    cvss: 7.4,
    confidence: 88,
    cwe: 'CWE-79',
    affected: '/support/ticket/{id}',
    description: 'Ticket title field renders user input without encoding, allowing persistent script execution in agent browsers.',
    businessImpact: 'Session hijacking of support agents, potential exposure of internal admin tools accessed from the same browser context.',
    threatIntel: 'Actively exploited pattern. XSS in support tools commonly used for helpdesk compromise chains.',
    remediation: 'Implement context-aware output encoding. Apply Content-Security-Policy headers. Sanitize rich text input server-side.',
    attackPath: [
      { step: '1', detail: 'Attacker creates a support ticket with malicious JS in the title' },
      { step: '2', detail: 'Support agent opens the ticket, executing the script' },
      { step: '3', detail: 'Script exfiltrates agent session cookie to attacker server' },
    ],
  },
  {
    id: 'VULN-004',
    title: 'Insecure Direct Object Reference — User Profiles',
    severity: 'High',
    cvss: 7.5,
    confidence: 90,
    cwe: 'CWE-639',
    affected: '/api/v2/users/{id}',
    description: 'User profile endpoint does not validate that the requester owns the requested ID, allowing enumeration of all user profiles.',
    businessImpact: 'Mass PII exposure. Violates GDPR and CCPA. Enables targeted phishing with harvested details.',
    threatIntel: 'Common precursor to social engineering campaigns. No active exploitation yet detected.',
    remediation: 'Enforce authorization checks on every object access. Implement indirect object references or UUID-based identifiers.',
    attackPath: [
      { step: '1', detail: 'Attacker iterates user IDs from 1 to N on /api/v2/users/{id}' },
      { step: '2', detail: 'Collects full name, email, phone, and address for each user' },
    ],
  },
  {
    id: 'VULN-005',
    title: 'Missing Rate Limiting on Password Reset',
    severity: 'Medium',
    cvss: 5.3,
    confidence: 85,
    cwe: 'CWE-307',
    affected: '/api/v2/auth/reset',
    description: 'Password reset endpoint accepts unlimited requests, enabling user enumeration via response timing and account lockout abuse.',
    businessImpact: 'User enumeration for targeted attacks. Denial of service against specific user accounts.',
    threatIntel: 'Routine technique. Often combined with credential stuffing in automated campaigns.',
    remediation: 'Implement rate limiting per IP and per account. Add CAPTCHA after threshold. Return generic responses regardless of email validity.',
    attackPath: [
      { step: '1', detail: 'Attacker sends reset requests to enumerate valid emails via timing differences' },
      { step: '2', detail: 'Valid emails used in credential stuffing attacks' },
    ],
  },
  {
    id: 'VULN-006',
    title: 'Outdated TLS Configuration on Legacy Subdomain',
    severity: 'Medium',
    cvss: 5.9,
    confidence: 100,
    cwe: 'CWE-326',
    affected: 'legacy.acmecorp.io',
    description: 'Subdomain supports TLS 1.0 and weak cipher suites, enabling downgrade attacks against legacy clients.',
    businessImpact: 'Potential interception of traffic to legacy systems. Compliance failure under PCI-DSS requirements.',
    threatIntel: 'Passive. No active exploitation, but routinely scanned by automated botnets.',
    remediation: 'Disable TLS 1.0/1.1. Restrict cipher suites to modern standards. Redirect legacy traffic to upgraded endpoints.',
    attackPath: [
      { step: '1', detail: 'Attacker forces TLS 1.0 handshake via downgrade' },
      { step: '2', detail: 'Performs BEAST or POODLE attack to decrypt session traffic' },
    ],
  },
  {
    id: 'VULN-007',
    title: 'Verbose Error Messages Expose Stack Traces',
    severity: 'Low',
    cvss: 3.7,
    confidence: 95,
    cwe: 'CWE-209',
    affected: '/api/v2/*',
    description: 'Unhandled exceptions return full stack traces including library versions and internal file paths.',
    businessImpact: 'Information leakage that accelerates targeted attacks by revealing the technology stack.',
    threatIntel: 'No direct exploitation. Used as reconnaissance input by attackers.',
    remediation: 'Implement global exception handler returning generic errors. Log detailed errors server-side only.',
    attackPath: [
      { step: '1', detail: 'Attacker sends malformed input to trigger exception' },
      { step: '2', detail: 'Reads stack trace to identify framework versions' },
    ],
  },
  {
    id: 'VULN-008',
    title: 'Missing Security Headers',
    severity: 'Low',
    cvss: 3.1,
    confidence: 100,
    cwe: 'CWE-693',
    affected: 'Global',
    description: 'Responses omit X-Content-Type-Options, X-Frame-Options, and Content-Security-Policy headers.',
    businessImpact: 'Increases susceptibility to clickjacking and MIME-type confusion attacks.',
    threatIntel: 'No active exploitation. Standard hardening gap.',
    remediation: 'Add standard security headers via middleware or web server configuration.',
    attackPath: [
      { step: '1', detail: 'Attacker embeds authenticated app in an iframe' },
      { step: '2', detail: 'Performs clickjacking to trigger privileged actions' },
    ],
  },
];

export const discoveryLogs = [
  'Initializing ATLAS Orchestrator...',
  'Resolving target DNS records...',
  'Discovering subdomains via passive sources...',
  'Enumerating DNS: 14 subdomains found',
  'Probing for live hosts...',
  '12 hosts responded to probes',
  'Enumerating endpoints via content discovery...',
  'Mapping application routes and API surface...',
  'Identifying technologies: nginx, Express, PostgreSQL',
  'Discovery phase complete — 47 assets catalogued',
];

export const vaLogs = [
  'Loading vulnerability detection rules...',
  'Running OWASP Top 10 checks...',
  'Testing injection points on 47 endpoints...',
  'Testing authentication mechanisms...',
  'Testing session management...',
  'Testing access control on 23 endpoints...',
  'Testing cryptographic implementations...',
  'Testing security headers and TLS...',
  'Vulnerability assessment complete — 8 findings',
];

export const validationLogs = [
  'Engaging AI validation engine...',
  'Reproducing finding VULN-001...',
  'Confirmed: SQL Injection — authentication bypass verified',
  'Reproducing finding VULN-002...',
  'Confirmed: JWT forgery verified with extracted secret',
  'Reproducing finding VULN-003...',
  'Confirmed: Stored XSS executes in agent context',
  'Reproducing finding VULN-004...',
  'Confirmed: IDOR allows cross-tenant access',
  'Reproducing finding VULN-005...',
  'Confirmed: Rate limiting absent',
  'Reproducing finding VULN-006...',
  'Confirmed: TLS 1.0 negotiation successful',
  'Reproducing finding VULN-007...',
  'Confirmed: Stack trace exposed on malformed input',
  'Reproducing finding VULN-008...',
  'Confirmed: Security headers absent',
  'False positive removal: 0 findings discarded',
  'AI validation complete — 8 confirmed vulnerabilities',
];

export const reportLogs = [
  'Aggregating validated findings...',
  'Correlating with threat intelligence feeds...',
  'Calculating dynamic risk scores...',
  'Generating executive summary...',
  'Compiling technical details and evidence...',
  'Formatting report for export...',
  'Executive report generated successfully',
];

export const pentestLogs = [
  'ATLAS Pentest Agent initialized',
  'Target: https://api.acmecorp.io',
  'Scope: confirmed exploitable vulnerabilities',
  '--- Phase 1: Authentication Testing ---',
  'Testing authentication bypass...',
  'Attempting SQL Injection on /api/v2/auth/login...',
  'SUCCESS: Authentication bypass confirmed',
  'Extracting database schema via UNION queries...',
  'Found table: users (12,847 rows)',
  'Found table: payment_tokens (3,201 rows)',
  '--- Phase 2: Session Exploitation ---',
  'Extracting JWT signing key from frontend bundle...',
  'Forging admin JWT token...',
  'SUCCESS: Admin token accepted at /api/v2/admin/*',
  '--- Phase 3: Business Logic Testing ---',
  'Testing price manipulation in checkout flow...',
  'Testing bulk-discount logic abuse...',
  'Found: Negative quantity accepted in cart API',
  '--- Phase 4: Attack Chain Discovery ---',
  'Chaining SQLi + JWT forgery for full account takeover...',
  'Chaining IDOR + XSS for support agent compromise...',
  '--- Phase 5: Evidence Collection ---',
  'Capturing HTTP request/response pairs...',
  'Capturing screenshots of exploitation...',
  'Generating proof-of-concept scripts...',
  '--- Phase 6: Exploitation Results ---',
  '3 new vulnerabilities discovered via pentest',
  '2 attack chains documented',
  'Pentest complete — evidence packaged',
];

export const aiAnalysisLogs = [
  'ATLAS deep analysis initiated...',
  '✔ Business Context: Processing asset criticality and data sensitivity',
  '✔ Business Context: Identified 4 crown-jewel assets',
  '✔ Threat Intelligence: Querying 14 threat feeds',
  '✔ Threat Intelligence: 3 findings matched active exploits',
  '✔ Dynamic Risk Ranking: Computing CVSS + business impact scores',
  '✔ Dynamic Risk Ranking: Prioritized 11 vulnerabilities',
  '✔ Executive Report: Generating final deliverable',
  '✔ Executive Report: Ready for download',
];
