import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText, Download, Loader2, CheckCircle2, ShieldAlert,
  Server, BarChart3, Bug, Scale, Lightbulb, Lock,
} from 'lucide-react';
import type { Finding, Severity } from '../data';
import { SEVERITY_META, DISCOVERY_RESULT } from '../data';
import type { LucideIcon } from 'lucide-react';
import BrandLogo from './BrandLogo';

interface ExecutiveReportProps {
  findings: Finding[];
  severityCounts: Record<Severity, number>;
  totalFindings: number;
  target: string;
  assessmentComplete: boolean;
  generating: boolean;
  reportReady: boolean;
  onGenerate: () => void;
  onDownload: () => void;
}

export default function ExecutiveReport({
  findings, severityCounts, totalFindings, target, assessmentComplete, generating, reportReady, onGenerate, onDownload,
}: ExecutiveReportProps) {
  const [downloaded, setDownloaded] = useState(false);

  const critical = severityCounts.critical || 0;
  const high = severityCounts.high || 0;
  const riskScore = Math.min(100, Math.round((critical * 25 + high * 12 + (severityCounts.medium || 0) * 5 + (severityCounts.low || 0) * 1) / Math.max(1, totalFindings) * 10));
  const riskLevel = riskScore >= 75 ? 'Critical' : riskScore >= 50 ? 'High' : riskScore >= 25 ? 'Medium' : 'Low';
  const riskColor = riskLevel === 'Critical' ? '#ff4444' : riskLevel === 'High' ? '#f97316' : riskLevel === 'Medium' ? '#eab308' : '#60a5fa';

  const handleDownload = () => {
    onDownload();
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2500);
  };

  const recommendations = [
    'Immediately remediate the Remote Code Execution vulnerability by removing unsafe deserialization paths and enforcing strict input validation.',
    'Patch the SQL injection in the authentication flow using parameterized queries and deploy a Web Application Firewall as interim mitigation.',
    'Remove the exposed .env file from the public web root and rotate all leaked credentials (database, API keys) immediately.',
    'Enforce a strong password policy (min. 12 chars, mixed case, digits, symbols) and implement account lockout with rate limiting.',
    'Add security headers (HSTS, CSP, X-Frame-Options) at the reverse proxy and disable deprecated TLS 1.0/1.1 protocols.',
    'Upgrade Nginx to the latest stable release to remediate CVE-2024-7347 and establish a continuous patch management cadence.',
  ];

  return (
    <div className="glass-card-bright rounded-2xl overflow-hidden">
      <div className="flex items-center justify-between px-5 py-4 border-b border-crimson-500/10 bg-crimson-950/20">
        <div className="flex items-center gap-3">
          <FileText size={20} className="text-crimson-400" />
          <div>
            <h2 className="text-base font-600 text-crimson-100">Executive Report Preview</h2>
            <p className="text-[11px] text-crimson-300/50">AI-generated assessment summary for stakeholders</p>
          </div>
        </div>
        <span className="text-[10px] text-crimson-400/50 uppercase tracking-wider">Confidential</span>
      </div>

      <div className="p-5 md:p-8">
        {/* Report cover */}
        <div className="relative rounded-xl overflow-hidden mb-6 bg-gradient-to-br from-crimson-950 via-surface-400 to-surface-500 p-8 border border-crimson-500/20">
          <div className="absolute inset-0 bg-grid opacity-30" />
          <div className="absolute -top-10 -right-10 w-40 h-40 bg-crimson-700/20 rounded-full blur-3xl" />
          <div className="relative z-10 flex items-center gap-4 mb-4">
            <BrandLogo size={48} />
            <div>
              <p className="font-cinzel font-700 text-2xl tracking-[0.2em] text-crimson-200 text-glow-red">ATLAS</p>
              <p className="text-[10px] tracking-[0.3em] text-crimson-400/50 uppercase">Vulnerability Assessment Report</p>
            </div>
          </div>
          <h3 className="text-xl font-600 text-crimson-100 mb-1">Security Assessment — {target}</h3>
          <p className="text-xs text-crimson-300/50">Generated by ATLAS Sentinel AI · {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          <div className="flex items-center gap-3 mt-4">
            <div className="px-3 py-1 rounded-full glass-card text-xs text-crimson-200/80">Prototype v1</div>
            <div className="px-3 py-1 rounded-full glass-card text-xs" style={{ color: riskColor, border: `1px solid ${riskColor}40` }}>
              Risk: {riskLevel}
            </div>
          </div>
        </div>

        {/* Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <Section icon={FileText} title="Executive Summary">
            <p className="text-sm text-crimson-200/70 leading-relaxed">
              An automated vulnerability assessment was performed against <span className="text-crimson-300 font-500">{target}</span> covering infrastructure discovery, security configuration review, and CVE correlation. The assessment identified <span className="text-crimson-300 font-600">{totalFindings} vulnerabilities</span>, including <span className="text-crimson-400 font-600">{critical} critical</span> and <span className="text-orange-400 font-600">{high} high-severity</span> issues requiring immediate attention. The overall risk posture is classified as <span style={{ color: riskColor }} className="font-600">{riskLevel}</span>.
            </p>
          </Section>

          <Section icon={Server} title="Infrastructure Overview">
            <ul className="text-sm text-crimson-200/70 space-y-1">
              <li><span className="text-crimson-300/50">Target:</span> <span className="font-mono text-crimson-200">{target}</span></li>
              <li><span className="text-crimson-300/50">Resolved IPs:</span> <span className="font-mono text-crimson-200">{DISCOVERY_RESULT.dns.ips.join(', ')}</span></li>
              <li><span className="text-crimson-300/50">Open Ports:</span> <span className="font-mono text-crimson-200">{DISCOVERY_RESULT.ports.filter(p => p.state === 'open').length}</span></li>
              <li><span className="text-crimson-300/50">Technologies:</span> <span className="text-crimson-200">{DISCOVERY_RESULT.technologies.length} detected</span></li>
              <li><span className="text-crimson-300/50">TLS:</span> <span className="font-mono text-crimson-200">{DISCOVERY_RESULT.ssl.protocol}</span></li>
            </ul>
          </Section>

          <Section icon={BarChart3} title="Assessment Statistics">
            <div className="grid grid-cols-2 gap-2">
              <Stat label="Discovery Tasks" value="7" />
              <Stat label="Assessment Checks" value="8" />
              <Stat label="Ports Scanned" value="65,535" />
              <Stat label="Endpoints Found" value={String(DISCOVERY_RESULT.endpoints.length)} />
              <Stat label="Total Findings" value={String(totalFindings)} />
              <Stat label="Risk Score" value={`${riskScore}/100`} color={riskColor} />
            </div>
          </Section>

          <Section icon={Bug} title="Detected Vulnerabilities">
            <div className="space-y-1.5">
              {(['critical', 'high', 'medium', 'low', 'info'] as Severity[]).map((sev) => (
                <div key={sev} className="flex items-center justify-between text-sm">
                  <span className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full" style={{ background: SEVERITY_META[sev].color }} />
                    <span className="text-crimson-200/70">{SEVERITY_META[sev].label}</span>
                  </span>
                  <span className="font-600 font-cinzel" style={{ color: SEVERITY_META[sev].color }}>{severityCounts[sev] || 0}</span>
                </div>
              ))}
            </div>
          </Section>

          <Section icon={Scale} title="Risk Summary">
            <p className="text-sm text-crimson-200/70 leading-relaxed mb-3">
              The composite risk score is <span style={{ color: riskColor }} className="font-700">{riskScore}/100</span>, indicating a <span style={{ color: riskColor }} className="font-600">{riskLevel}</span> risk level. Critical findings expose the organization to remote code execution, credential theft, and authentication bypass. Immediate remediation is advised to reduce exposure to active exploitation.
            </p>
            <div className="h-2 rounded-full bg-crimson-950/60 overflow-hidden">
              <motion.div
                className="h-full rounded-full"
                style={{ background: `linear-gradient(90deg, ${riskColor}, ${riskColor}80)` }}
                initial={{ width: 0 }}
                animate={{ width: `${riskScore}%` }}
                transition={{ duration: 1, ease: 'easeOut' }}
              />
            </div>
          </Section>

          <Section icon={Lightbulb} title="Recommendations" full>
            <ol className="text-sm text-crimson-200/70 space-y-2 list-decimal list-inside">
              {recommendations.map((r, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="leading-relaxed"
                >
                  {r}
                </motion.li>
              ))}
            </ol>
          </Section>
        </div>

        {/* Action area */}
        <div className="mt-6 flex flex-col sm:flex-row items-center justify-between gap-4 pt-5 border-t border-crimson-500/10">
          <div className="flex items-center gap-2 text-xs text-crimson-300/50">
            <Lock size={12} />
            <span>Report encrypted with AES-256 · Signed by ATLAS Sentinel</span>
          </div>
          <div className="flex items-center gap-3">
            {!assessmentComplete && (
              <span className="text-xs text-crimson-300/40">Report available after assessment completes</span>
            )}
            {assessmentComplete && !reportReady && !generating && (
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={onGenerate}
                className="btn-crimson px-5 py-2.5 rounded-lg text-sm font-600 text-white flex items-center gap-2"
              >
                <FileText size={16} /> Generate Report
              </motion.button>
            )}
            {generating && (
              <div className="flex items-center gap-2 px-5 py-2.5 rounded-lg glass-card text-sm text-crimson-200">
                <Loader2 size={16} className="animate-spin text-crimson-400" />
                Compiling report...
              </div>
            )}
            {reportReady && (
              <motion.button
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleDownload}
                className="btn-crimson px-5 py-2.5 rounded-lg text-sm font-600 text-white flex items-center gap-2 glow-red"
              >
                <AnimatePresence mode="wait">
                  {downloaded ? (
                    <motion.span key="done" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-center gap-2">
                      <CheckCircle2 size={16} /> Downloaded
                    </motion.span>
                  ) : (
                    <motion.span key="dl" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-center gap-2">
                      <Download size={16} /> Download PDF Report
                    </motion.span>
                  )}
                </AnimatePresence>
              </motion.button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ icon: Icon, title, children, full }: { icon: LucideIcon; title: string; children: React.ReactNode; full?: boolean }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`glass-card rounded-xl p-4 ${full ? 'lg:col-span-2' : ''}`}
    >
      <div className="flex items-center gap-2 mb-3">
        <Icon size={14} className="text-crimson-400" />
        <h4 className="text-xs uppercase tracking-wider text-crimson-300/70 font-600">{title}</h4>
      </div>
      {children}
    </motion.div>
  );
}

function Stat({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <div className="flex items-center justify-between px-2 py-1.5 rounded-lg bg-crimson-950/40">
      <span className="text-[11px] text-crimson-300/50">{label}</span>
      <span className="text-sm font-700 font-cinzel" style={{ color: color || '#f5f0f0' }}>{value}</span>
    </div>
  );
}
